"use client";
import { useActionState } from "react";
import { saveCompanySettings } from "@/lib/actions";
import { FieldError, FormError } from "@/components/FieldError";
import { SubmitButton } from "@/components/SubmitButton";

type Settings = { legalName: string; displayMonths: number; blankMonths: number; showGoal: boolean; yellowGood: boolean; redGood: boolean; chronicRedMonths: number; fixedBaseDate: string | null; automationDisabled: boolean };
export function CompanySettingsForm({ settings }: { settings: Settings }) {
  const [state, formAction] = useActionState(saveCompanySettings, null);
  return <form noValidate action={formAction} className="card max-w-3xl overflow-hidden"><div className="space-y-5 p-5 sm:p-6"><FormError message={state?.error} /><label className="flex flex-col gap-1.5"><span className="field-label">Nome da empresa</span><input name="legalName" defaultValue={settings.legalName} className="input-field" required/><FieldError message={state?.fieldErrors?.legalName}/></label><div className="grid gap-4 sm:grid-cols-3"><label className="flex flex-col gap-1.5"><span className="field-label">Meses exibidos</span><input name="displayMonths" type="number" min="1" max="24" defaultValue={settings.displayMonths} className="input-field"/></label><label className="flex flex-col gap-1.5"><span className="field-label">Meses em branco</span><input name="blankMonths" type="number" min="0" max="24" defaultValue={settings.blankMonths} className="input-field"/></label><label className="flex flex-col gap-1.5"><span className="field-label">Vermelho crônico</span><input name="chronicRedMonths" type="number" min="1" max="24" defaultValue={settings.chronicRedMonths} className="input-field"/></label></div><label className="flex max-w-xs flex-col gap-1.5"><span className="field-label">Data base fixa</span><input name="fixedBaseDate" type="month" defaultValue={settings.fixedBaseDate ?? ""} className="input-field"/></label><fieldset className="grid gap-3 border-t border-[var(--color-border)] pt-5 sm:grid-cols-2">{[["showGoal","Exibir meta nas grades",settings.showGoal],["yellowGood","Tratar amarelo como bom",settings.yellowGood],["redGood","Tratar vermelho como bom",settings.redGood],["automationDisabled","Desativar automações da empresa",settings.automationDisabled]].map(([name,label,checked]) => <label key={String(name)} className="flex items-center gap-2 text-[12.5px] text-[var(--color-ink-700)]"><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)} className="h-4 w-4 accent-[var(--color-brand-600)]"/>{String(label)}</label>)}</fieldset></div><div className="flex justify-end border-t border-[var(--color-border)] bg-[var(--color-surface-muted)] p-4"><SubmitButton>Salvar configurações</SubmitButton></div></form>;
}
